import os
import sys


def generate_entity_file(src, dst, type_name, pack_name="game_types"):
    found_files = []

    # verify source directory exists
    if not os.path.exists(src):
        print(f"Error: Source directory '{src}' does not exist.")
        return []

    for _, _, files in os.walk(src):
        for filename in files:
            if filename == "generated_registry.odin":
                continue
            # get filename without extension
            stem = os.path.splitext(filename)[0]
            # capitalize to match LDtk
            stem = stem.capitalize()
            found_files.append(stem)

    if not found_files:
        print(f"No files found in: {src}")
        return []

    # for deterministic output
    found_files.sort()

    os.makedirs(os.path.dirname(dst), exist_ok=True)

    try:
        with open(dst, "w", encoding="utf-8") as f:
            f.write("//NOTE: Machine generated by python script\n")
            f.write("\n")
            f.write(f"package {pack_name}\n")
            f.write("\n")
            f.write(f"{type_name}Name :: enum {{\n")
            f.write("\tnil,\n")
            for name in found_files:
                f.write(f"\t{name},\n")
            f.write("}\n\n")
    except IOError as e:
        print(f"Error on asset generation output: {e}", file=sys.stderr)

    # generate registry

    reg_dir = os.path.join(src, "generated_registry.odin")

    os.makedirs(os.path.dirname(reg_dir), exist_ok=True)

    try:
        with open(reg_dir, "w", encoding="utf-8") as f:
            f.write("//NOTE: Machine generated by python script\n")
            f.write("\n")
            f.write("package entityData")
            f.write("\n\n")
            f.write('import "bonsai:systems/entities"')
            f.write("\n\n")
            f.write(f"spawn := [entities.{type_name}Name]entities.SpawnProc {{\n")
            f.write("\t.nil = nil,\n")
            for name in found_files:
                f.write(f"\t.{name} = spawn{name},\n")
            f.write("}\n")
    except IOError as e:
        print(f"Error on asset registry generation output: {e}", file=sys.stderr)

    return found_files


if __name__ == "__main__":
    generate_entity_file(
        src="source/game/entities",
        dst="bonsai/systems/entities/generated_entity.odin",
        type_name="Entity",
        pack_name="entities",
    )
